[workspace]
authors = ["qi-xmu <360141773@qq.com>"]
channels = ["conda-forge"]
name = "mac-right-menu"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
rpc-debug = "python tests/rpc-debug/rpc_debug_server.py"
install = "bash ./Scripts/build-install.sh"

[dependencies]
python = ">=3.12"
rich = ">=13.0"
typer = ">=0.12"
pytest = ">=8.0"
